### ISSUE TITLE
User auth review

### ISSUE THREAD

**Issue by mufasubhai** [mufasubhai/situo#2]
Due to the standard flow on Asana, I decided to do a slightly modified login flow. 

as a result, the root page renders a clone of this [page.](https://asana.com/?utm_source=unknown&utm_campaign=app.asana.com#close) Sign up and Log in are clones of [this page](https://app.asana.com/app/asana/-/login)

[The site can be found here.](http://situo.herokuapp.com/)

# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds (currently the only seeds are for demo login & additional users who will be built out later)

**Comment by jenvomo** [comment]
AWESOME job @mufasubhai!

Just a couple small things left unchecked above - also:
- [x] Vertically center / align email icon in navbar on splash page
- [x] Use a color for the font color of error messages in session form
- [x] Add favicon

**Comment by mufasubhai** [comment]
Should be updated. Take a look when you have a chance!

**Comment by jenvomo** [comment]
Almost everything is good to go! The errors take up a lot of space and move the input fields on the session form a lot when they come up. Modify this so that the errors take of less space and nothing on the page is moving when they render

**Comment by jenvomo** [comment]
Great job!
